In [ ]:
# Implementing a Basic Reinforcement Learning Model (Q-Learning)

import numpy as np
import gymnasium as gym

# Creating FrozenLake Environment (this environment is deterministic for easier learning)
env = gym.make("FrozenLake-v1", is_slippery=False)

# Initialize Q-table
state_size = env.observation_space.n
action_size = env.action_space.n
q_table = np.zeros((state_size, action_size))

# Hyperparameters
learning_rate = 0.8
discount_factor = 0.95
episodes = 10000

# Exploration settings
epsilon = 1.0          # start with full exploration
epsilon_decay = 0.995
min_epsilon = 0.01

# Training using Q-Learning
for episode in range(episodes):
    state, _ = env.reset()
    done = False

    while not done:

        # Epsilon-greedy strategy
        if np.random.rand() < epsilon:
            action = env.action_space.sample()
        else:
            action = np.argmax(q_table[state])

        next_state, reward, terminated, truncated, _ = env.step(action)
        done = terminated or truncated

        # Q-learning update rule
        old_value = q_table[state, action]
        next_max = np.max(q_table[next_state])

        new_value = (1 - learning_rate) * old_value + \
                    learning_rate * (reward + discount_factor * next_max)

        q_table[state, action] = new_value
        state = next_state

    # Reduce exploration gradually
    epsilon = max(min_epsilon, epsilon * epsilon_decay)

print("Trained Q-table:\n")
print(q_table)

# Testing the trained agent
state, _ = env.reset()
done = False
total_reward = 0

while not done:
    action = np.argmax(q_table[state])
    state, reward, terminated, truncated, _ = env.step(action)
    done = terminated or truncated
    total_reward += reward

print("\nTotal Reward after training:", total_reward)


Trained Q-table:

[[0.73509189 0.77378094 0.6983373  0.73509189]
 [0.73509189 0.         0.         0.49642252]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.77378094 0.81450625 0.         0.73509189]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.81450625 0.         0.857375   0.77378094]
 [0.81450625 0.9025     0.9025     0.        ]
 [0.84903928 0.95       0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9025     0.95       0.857375  ]
 [0.9025     0.95       1.         0.9025    ]
 [0.         0.         0.         0.        ]]

Total Reward after training: 1
